# Default configuration for Webserv

server {
    listen 127.0.0.1:8088;
    server_name localhost;

    root www;
    index index.html;
    error_page 404 /404.html;
    client_max_body_size 30M;

    location / {
        index index.html;
        autoindex off;
        allowed_methods GET POST;
    }

    location /upload {
        root www/upload;
        allowed_methods POST;
        client_max_body_size 10000000;
    }

    location /delete-me {
        root www/delete-me;
        allowed_methods DELETE;
    }

    location /cgi-bin {
        cgi_pass /cgi-bin/;
        allowed_methods GET POST;
    }
}
