# Default configuration for Webserv

server {
# <<<<<<< HEAD
    listen 127.0.0.1:8080;
# =======
    listen localhost:8080;
# >>>>>>> 29eec99dd30bc7d6dcc4c491a2b18e7bdcadca34
    server_name localhost;

    root www;
    index index.html;
    error_page 404 /404.html;
    client_max_body_size 30M;

    location /dsk  {
        index index.html;
        autoindex off;
        allowed_methods GET POST;
    }

	location ^~ /static/ { 
        root www/sssss;
        index index.html;
        autoindex off;
        allowed_methods GET POST;
    }

    location ^~ /static { 
        index index.html;
        autoindex off;
        allowed_methods GET POST;
    }

    location /upload {
        root www/upload;
        allowed_methods POST;
        client_max_body_size 10000000;
    }

    location /delete-me {
        root www/delete-me;
        allowed_methods DELETE;
    }

    location /cgi-bin {
        cgi_pass /cgi-bin/;
        allowed_methods GET POST;
    }
}
