# Default configuration for web2

server {


	listen localhost:8080;

	server_name localhost;
	# problem in root and index + in two servers with the same port number;(no binding)
	root /home/mlabyed/;
	index index.html;
    error_page 200 www/200.html;
    error_page 400 www/400.html;
    error_page 403 www/403.html;
    error_page 404 www/404.html;
    error_page 405 www/405.html;
    error_page 413 www/413.html;
    error_page 408 www/408.html;
    error_page 409 www/409.html;
    error_page 201 www/201.html;
    error_page 204 www/204.html;
    error_page 500 www/500.html;
    error_page 502 www/502.html;
    error_page 503 www/503.html;
    error_page 504 www/504.html;
    error_page 505 www/505.html;
    error_page 431 www/431.html;
    error_page 501 www/501.html;
    error_page 411 www/411.html;    


    client_max_body_size 99G;

    location / {
    	    root /home;
            upload_store /mlabyed/goinfre;
            index index.html;
            allowed_methods GET DELETE POST;
            autoindex on;
            # return 302 /images/home;
            cgi_pass .py /usr/bin/python3;
	    }

        location /images/home {
    	    # root /home/mlabyed/images;
            index default.jpg;
            allowed_methods GET POST;
            # allowed_methods POST;
            #  return 302 /;
            cgi_pass .py /usr/bin/python3;
        }
	    


	location  /images {
    	    root /home/mlabyed/images;
            upload_store /;
            index file.html;
            client_max_body_size 5K;
            autoindex off;
            # return 302 /;

    }	    


    # location /static/diir/images { 
    #     index index.html;
    #     autoindex off;
    #     allowed_methods GET POST;
    # }

    location /upload {
         root /home/mlabyed;
        upload_store /Desktop/web2/www/upload;
        #root /home/1webserv;
        
        allowed_methods GET POST;
        client_max_body_size 10000000;
        autoindex on;
    }

    location /delete-me {
        root home/mlabyed/folder;
        allowed_methods DELETE;
    }

    location /cgi-bin {
        root www;
        upload_store /upload/;
        index time.py;
        cgi_pass .py /usr/bin/python3;
        cgi_pass .php /usr/bin/php-cgi;
        #cgi_pass .html /usr/bin/php-cgi;
        cgi_pass .pl  /usr/bin/perl;
        allowed_methods GET POST;
    }
}

# server
# 	listen 10.14.9.4:8090;
# 	index index.html;
#    error_page 200 www/200.html;
#      error_page 400 www/400.html;
#     error_page 403 www/403.html;
#     error_page 404 www/404.html;
#     error_page 405 www/405.html;
#     error_page 413 www/413.html;
#     error_page 408 www/408.html;
#     error_page 409 www/409.html;
#     error_page 201 www/201.html;
#     error_page 204 www/204.html;
#     error_page 500 www/500.html;
#     error_page 502 www/502.html;
#     error_page 503 www/503.html;
#     error_page 504 www/504.html;
#     error_page 505 www/505.html;
#     error_page 431 www/431.html;
#     error_page 501 www/501.html;
#     error_page 411 www/411.html;  
# 	server_name salma;
# 	root anannn;
# 	# index heee.lo;
#     client_max_body_size 1M;
#     index file.html;
# 	# error_page 444 file.html;
# 	    location / {
#     	    root /home/mlabyed/images;
#             index cat.jpg;
#             allowed_methods  DELETE;
#             autoindex on;
# 	    }

# server
# 	listen 10.14.0.2:8080;
# 	server_name salma;
# 	root anannn;
# 	# index heee.lo;
#     index file.html;
# 	# error_page 444 file.html;
# 	    location / {
#     	    root /home/salaoui/images;
#             index cat.jpg;
#             allowed_methods GET DELETE;
#             autoindex on;
# 	    }

