# Default configuration for Webserv

server {

	listen 127.0.0.1:8080;
	server_name localhost;
	# problem in root and index + in two servers with the same port number;(no binding)
	root www;
	index index.html;
    error_page 403 www/403.html;
    error_page 404 www/404.html;
    error_page 405 www/405.html;
    error_page 413 www/413.html;
    client_max_body_size 30M;

    location / {
    	    root /home/salaoui;
            index file.html;
            allowed_methods GET DELETE POST;
            autoindex on;
	    }
    location /images/home {
    	    root /home/salaoui/images;
            index default.jpg;
            allowed_methods GET POST;
            # allowed_methods POST;
	    }

	location  /images 
    	    root /home/salaoui/images;
            index file.html;
            client_max_body_size 5K;
            autoindex on;
	    


    # location /static/diir/images { 
    #     index index.html;
    #     autoindex off;
    #     allowed_methods GET POST;
    # }

    location /upload {
        root /home/salaoui/Desktop/webserv/www/upload;
        allowed_methods GET POST;
        client_max_body_size 10000000;
    }

    location /delete-me {
        root home/salaoui/folder;
        allowed_methods DELETE;
    }

    location /cgi-bin {
        root /home/salaoui/Desktop/webserv/cgi-bin;
        index time.py;
        cgi_pass /cgi-bin/;
        allowed_methods GET POST;
    }
}

# server
# 	listen localhost:8181;
# 	server_name salma;
# 	root anannn;
# 	# index heee.lo;
#     index index.html;
# 	error_page 444 file.html;
# 	    location / {
#     	    root /;
#             index cat.jpg;
#             allowed_methods GET DELETE;
#             autoindex on;
# 	    }
