# Default configuration for Webserv

server {

	listen localhost:8083; 
	server_name localhost;
	root www; 
	# index fiile.html;
    # error_page 400 www/400.html;
    # error_page 403 www/403.html;
    # error_page 404 www/404.html;
    # error_page 405 www/405.html;
    # error_page 408 www/408.html;
    # error_page 413 www/413.html;
    # error_page 409 www/409.html;
    # error_page 201 www/201.html;
    # error_page 204 www/204.html;
    # error_page 500 www/500.html;
    # error_page 502 www/502.html;
    # error_page 504 www/504.html;
    # error_page 503 www/503.html;
    # error_page 505 www/505.html;
    # error_page 431 www/431.html;
    # error_page 501 www/501.html;
    # error_page 411 www/411.html;
    client_max_body_size 10M;

    location / {  
    	    root www;
            upload_store www/upload/;
            index index.html;
            allowed_methods GET POST;
            autoindex on;
            return 301 /images;
            cgi_pass .py /usr/bin/python3;
	    }

        location /images {
    	    root /home/salaoui;
            upload_store webserv/www/upload;
            index index.html;
            allowed_methods GET POST;
            cgi_pass .py /usr/bin/python3;
        }
	    

    location /upload {
        # root /home/salaoui/Desktop/webserv/www/upload;
        index 152603497.jpeg;
        allowed_methods POST;
        client_max_body_size 10000000;
        autoindex on;
    }

    location /delete-me {
        root home/salaoui/folder;
        allowed_methods DELETE;
    }

    location /cgi-bin {
        root cgi-bin;
            upload_store www/upload/;
        # index time.py;
        cgi_pass .py /usr/bin/python3;
        cgi_pass .php /usr/bin/php-cgi;
        cgi_pass .pl  /usr/bin/perl;
        cgi_pass .sh  /bin/sh;
        allowed_methods GET POST;
    }
}

# server
# 	listen localhost:8081;
# 	root anannn;
# 	server_name asdfds;
# 	# index heee.lo;
#     index file.html;
# 	# error_page 444 file.html;
# 	    location / {
#     	    root /home/salaoui/images;
#             index cat.jpg;
#             allowed_methods GET DELETE;
#             autoindex on;
# 	    }
