# Default configuration for web2

server {
	listen localhost:8080;

	server_name localhost;
	root    www;
	index index.html;
    # error_page 200 error_pages/200.html;
    # error_page 400 error_pages/400.html;
    # error_page 403 error_pages/403.html;
    # error_page 404 error_pages/404.html;
    # error_page 405 error_pages/405.html;
    # error_page 413 error_pages/413.html;
    # error_page 408 error_pages/408.html;
    # error_page 409 error_pages/409.html;
    # error_page 201 error_pages/201.html;
    # error_page 204 error_pages/204.html;
    # error_page 500 error_pages/500.html;
    # error_page 502 error_pages/502.html;
    # error_page 503 error_pages/503.html;
    # error_page 504 error_pages/504.html;
    # error_page 505 error_pages/505.html;
    # error_page 431 error_pages/431.html;
    # error_page 501 error_pages/501.html;
    # error_page 411 error_pages/411.html;    


    client_max_body_size 46M;

    location / {
        root www;
        upload_store upload;
        index index.html;
        allowed_methods GET DELETE POST;
        autoindex on;
        # return 302 /upload;
        cgi_pass .py /usr/bin/python3;
    }

    location /upload {
        root www;
        upload_store upload;
        cgi_pass .py /usr/bin/python3;
        cgi_pass .php /usr/bin/php-cgi;
        cgi_pass .pl  /usr/bin/perl;
        allowed_methods GET POST;
        client_max_body_size 10000000;
        autoindex on;
    }


    location /cgi-bin {
        root www;
        upload_store /upload/;
        index hello.py;
        cgi_pass .py /usr/bin/python3;
        cgi_pass .php /usr/bin/php-cgi;
        cgi_pass .pl  /usr/bin/perl;
        allowed_methods GET POST;
    }
}

server
	listen localhost:8081;
	index index.html;
    error_page 200 error_pages/200.html;
    error_page 404 error_pages/404.html;
	server_name 200OkGirls;
	root www;

	    location / {
    	    root www;
            index index.html;
            allowed_methods GET DELETE;
            cgi_pass .py /usr/bin/python3;
            autoindex on;
	    }
