
server {
	listen  127.0.0.1:8090;
	server_name localhost;
	root www;
    error_page 200 error_pages/200.html;
    error_page 400 error_pages/400.html;
    error_page 403 error_pages/403.html;
    error_page 404 error_pages/404.html;
    error_page 405 error_pages/405.html;
    error_page 413 error_pages/413.html;
    error_page 408 error_pages/408.html;
    error_page 409 error_pages/409.html;
    error_page 201 error_pages/201.html;
    error_page 204 error_pages/204.html;
    error_page 500 error_pages/500.html;
    error_page 502 error_pages/502.html;
    error_page 503 error_pages/503.html;
    error_page 504 error_pages/504.html;
    error_page 505 error_pages/505.html;
    error_page 431 error_pages/431.html;
    error_page 501 error_pages/501.html;
    error_page 411 error_pages/411.html;    
    client_max_body_size 500M;

    location / {
    	    root www;
            upload_store upload;
            #return 302 /upload;
            allowed_methods GET DELETE POST;
            autoindex on;
            #return 302 /upload;
            cgi_pass .py /usr/bin/python3;
	    }

        location /images/home {

    	     root /home/wzahir/images;
            index default.jpg;
            allowed_methods GET POST;
            # allowed_methods POST;
            return 302 /images;
            cgi_pass .py /usr/bin/python3;
        }
	    


	location  /images {
    	    root /home/wzahir/images;
            index file.html;
            client_max_body_size 5K;
            autoindex off;
            # return 302 /;

    }	    


    location /upload {
        root www;
        autoindex on;
        upload_store www;
        allowed_methods GET POST DELETE;
        client_max_body_size 10000000;
    }

    location /delete-me {
        root home/wzahir/folder;
        allowed_methods DELETE;
    }

    location /cgi-bin {
         root cgi-bin;
        #  root cgi-bin;
        upload_store www/cgi-bin;
        index time.py;
        cgi_pass .py /usr/bin/python3;
        cgi_pass .php /usr/bin/php-cgi;
        cgi_pass .pl  /usr/bin/perl;
        cgi_pass .sh  /usr/bin/sh;
        allowed_methods GET POST;
    }
}

